#ArcGIS Pro project location
ESRI:
  root: ".\\.esri"
  aprx_name: "EditMaps.aprx"

# Edit version configuration
VERSIONING:
  parent_version: "SDE.DEFAULT"
  version_name: "UTIL_FloodplainEdits"
  access_permission: "PRIVATE"

# Data paths
DATA:
  urls:
    city: "https://maps.bouldercolorado.gov/arcgis/rest/services/plan/CityLimits/MapServer/0"
    nfhl: "https://hazards.fema.gov/gis/nfhl/rest/services/public/NFHL/MapServer"
    city_flood: "https://maps.bouldercolorado.gov/arcgis3/rest/services/util/Floodplain/MapServer/3"
  sde:
    spatialref: 2876 # NAD83(HARN) / Colorado North (ftUS)
    feature: 
      name: "GISPROD3.UTIL.FloodplainRegulatory"
      fields:
        - "FLOODZONE"
        - "FLOODWAY"
        - "DRAINAGE"
        - "EFFDATE"
        - "INEFFDATE"
        - "SOURCE"
        - "SHAPE@"

# Email recipients
EMAIL:
  lomr-notification:
    - "publicworksir@bouldercolorado.gov"
    - "floodpermits@bouldercolorado.gov"
    - "knappk@bouldercolorado.gov"
    - "olsenl@bouldercolorado.gov"
    - "colemanb@bouldercolorado.gov"
    - "shepc2@bouldercolorado.gov"
  data-steward:
    - "publicworksir@bouldercolorado.gov"

# Logging Configurations
LOGGING:
  version: 1
  formatters:
    only:
      format: '%(asctime)s.%(msecs)03d : %(name)s : %(levelname)s : %(message)s'
      datefmt: '%m/%d/%Y %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: only
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      level: INFO
      formatter: only
      filename: './floodplains/log/process.log'
    warnfile:
      class: logging.FileHandler
      level: WARNING
      formatter: only
      filename: './floodplains/log/errors.log'
    email:
      class: logging.handlers.SMTPHandler
      mailhost: ["smtp.office365.com", 587]
      fromaddr: "noreply@bouldercolorado.gov"
      subject: "An error halted the Floodplain script"
      secure: []
      level: ERROR
      formatter: only
  loggers:
    __main__:
      level: INFO
      handlers: [console, file, warnfile, email]
    floodplains.etl:
      level: INFO
      handlers: [console, file, warnfile]
    floodplains.utils.esriapi:
      level: INFO
      handlers: [console, file, warnfile]
    floodplains.utils.managedb:
      level: INFO
      handlers: [console, file, warnfile]
    floodplains.utils.managedisk:
      level: INFO
      handlers: [console, file, warnfile]
    floodplains.utils.editdb:
      level: INFO
      handlers: [console, file, warnfile]

# Database configurations, credentials in separate untracked file
DATABASE:
  connections:
    read: "S:\\GIS\\Share\\DatabaseConnections\\SQLGISProd3\\gis on gisprod3.sde"
    edit: "S:\\GIS\\Share\\DatabaseConnections\\SQLGISProd3\\secured_sde_files\\gisscr on gisprod3.sde"
  info:
    database_platform: "SQL_SERVER"
    instance: "GISData"
    database: "gisprod3"
    account_authentication: "DATABASE_AUTH"
    username: "gisscr"
    version_type: "TRANSACTIONAL"
